name: Deploy to AWS (CDK)

on:
  push:
    branches:
      - main
# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install CDK dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION}}
          role-to-assume: ${{ vars.AWS_GITHUB_ROLE}}

      - name: AWS Acount
        run: aws sts get-caller-identity

      - name: Install CDK
        run: npm install

      - name: Deploy CDK stack
        env:
          AWS_REGION: ${{ vars.AWS_REGION}}
        run:
          export CDK_DEFAULT_ACCOUNT=$(aws sts get-caller-identity | jq -r '.Account');
          npx cdk deploy --all --require-approval never
